### ISSUE TITLE
Incompatible with Sinytra Connector

### ISSUE THREAD

**Issue by uthw** [BareMinimumStudios/relicex#11]
This might already be in the process of being fixed, but I thought I'd might as well report it anyway.

1. Add RelicEx and Connector with all of their dependencies on Forge/NeoForge 1.20.1
2. Crash on loading screen

Log: https://mclo.gs/BTJyHLB

**Comment by karuzumi** [comment]
Confirmed. After investigating for a bit, this might be potentially an issue that is out of my ability to fix...

I would recommend reporting this to Sinytra Connector directly @ https://github.com/Sinytra/Connector/issues

In the case that this was not an issue on Connector's side, and was on mine, I'll pursue the issue further.

Also, from my findings, `relicex$matches` is the **only** issue preventing it from starting up it seems.

**Comment by uthw** [comment]
Understood. It seems like Connector is no longer doing compatibility patches for 1.20.1 so I'll wait to report this there until RelicEx is on 1.21. Thanks for your help :)
