### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by yahi-ko** [BareMinimumStudios/relicex#2]
Minecraft 1.20.1
i'm able to run playerex without relicex
w/ relicex this crash happens: https://pastebin.com/SSBNPb5e

i assume it's because of armor render lib inside relicex.

mods: 
	- ad_astra 1.15.5
	- advanced_runtime_resource_pack 0.8.1
	- advancementplaques 1.4.11
	- ae2 15.0.19
	- ae2mixin 1.0.0+1.20.1+fabric
	- ae2wtlib 15.2.1-fabric
	- alloy_forgery 2.1.2+1.20
	- alternate-current 1.7.0
	- ambientenvironment 11.0.0.1
	- ambientsounds 5.3.5
	- arbiters_weapons 1.1
	- arc 1.4.1
	- archers 1.0.6+1.20.1
	- architectury 9.1.12
	- armourers_workshop 2.0.11
	- autohud 6.3.3+1.20.1
	- autotag-convention 2.0.2+1.20
	- azurelib 2.0.18
	- azurelibarmor 2.0.3
	- backpacked 2.2.7
	- badoptimizations 1.6.2
	- bakery 1.1.3
	- balm-fabric 7.2.1
	- bbca 1.0.0
	- bclib 3.0.14
	- beachparty 1.1.3
	- beautify 1.1.0+1.20
	- bedbenefits 13.0.2
	- benched 1.2.2
	- betterbeds 1.3.0
	- betterchunkloading 1.20.1-2.6
	- betterclouds 1.3.13+1.20.1
	- bettercombat 1.8.3+1.20.1
	- betterend 4.0.11
	- betterfpsdist 1.20.1-4.0
	- betternether 9.0.10
	- blanket-client-tweaks 1.1.4
	- bookshelf 20.1.8
	- bosses_of_mass_destruction 1.7.5-1.20.1
	- botania 1.20.1-443-FABRIC
	- botarium 2.2.1
	- candlelight 1.2.8
	- cardinal-components 5.2.2
	- casualness_delight 1.20.1-0.3a
	- chatanimation 1.0.5
	- chunksending 1.20.1-2.8
	- chunksfadein 1.0.4-1.20.1
	- clientcrafting 1.20.1-1.7
	- cloth-config 11.1.118
	- clumps 12.0.0.3
	- cobblemon 1.4.1+1.20.1
	- collective 7.30
	- combatroll 1.3.0+1.20.1
	- comforts 6.3.4+1.20.1
	- connectivity 1.20.1-4.9
	- controlling 12.0.2
	- coroutil 1.20.1-1.3.5
	- cratedelight 1.2.7
	- create 0.5.1-d-build.5+mc1.20.1
	- create_new_age 1.1.1
	- createbigcannons 0.5.3.b-nightly-8a45d8e
	- createoreexcavation 1.4.3
	- creativecore 2.11.15
	- cristellib 1.1.5
	- ctov 3.3.6
	- culturalcreators 1.0.0
	- culturaldelights 0.14.11+1.20.1
	- cupboard 1.20.1-2.2
	- dataattributes_dc 1.6.0+1.20.1
	- debugify 1.20.1+2.0
	- deeperdarker 1.2.5
	- desolation 1.3.2
	- doapi 1.2.8
	- dungeon_difficulty 2.0.5+1.20.1
	- dungeons_arise 2.1.58
	- dungeons_arise_seven_seas 1.0.2
	- durabilitytooltip 1.1.5
	- dynamic_fps 3.3.2
	- dynamiccrosshair 7.4.2+1.20
	- dynamiccrosshaircompat 3.7.1+1.20.1
	- dynview 1.20.1-3.2
	- eco 2.4.1
	- enchanted-vertical-slabs 1.9.1
	- enchdesc 17.0.11
	- enhancedblockentities 0.9+1.20
	- enhancedvisuals 1.6.9
	- entity_texture_features 5.1.2
	- entityculling 1.6.2-mc1.20.1
	- epherolib 1.2.0
	- equipmentcompare 1.3.8
	- eugenes_guan_dao 1.0.0
	- everycomp 1.20-2.6.21
	- explorerscompass 1.20.1-2.2.3-fabric
	- extendedae 1.20-0.1.2-fabric
	- fabric-api 0.91.0+1.20.1
	- fabric-language-kotlin 1.10.17+kotlin.1.9.22
	- fabricloader 0.15.3
	- fakerlib 0.1.0
	- farmersdelight 1.20.1-1.4.3
	- farsight 1.20.1-4.2
	- fastasyncworldsave 1.20.1-1.3
	- faster_entity_animations 1.6
	- fastload 3.4.0
	- ferritecore 6.0.1
	- forgeconfigapiport 8.0.0
	- formations 1.0.2
	- formationsnether 1.0.3
	- formationsoverworld 1.0.2
	- framework 0.6.16
	- frozenlib 1.5.4-Fabric+1.20.1
	- fzzy_core 0.3.4+1.20.1
	- galosphere 1.20.1-1.4.1
	- galospheretrimming 1.20.1-1.0.0-quilt
	- gear_core 0.3.7+1.20.1
	- gearifiers 0.5.2+1.20.1
	- geckolib 4.3.1
	- generations_core 2.0.2-Beta
	- goblintraders 1.9.3
	- gpumemleakfix 1.20.1-1.8
	- herbalbrews 1.0.2
	- iceberg 1.1.18
	- immediatelyfast 1.2.8+1.20.4
	- indium 1.0.27+mc1.20.1
	- inventoryessentials 8.2.1
	- iris 1.6.11
	- itemborders 1.2.1
	- itemphysiclite 1.6.2
	- itemrestrictions 1.1.2
	- jade 11.7.0
	- jamlib 0.6.1+1.20.x
	- java 17
	- jei 15.2.0.27
	- jobsplus 1.3
	- justhammers 2.0.3+mc1.20.1
	- kiwi 11.4.0
	- knavesneeds 2.0.1+1.20.1
	- krypton 0.2.3
	- lambdynlights 2.3.2+1.20.1
	- lazy-language-loader 0.3.3
	- lazydfu 0.1.3
	- leaky 1.20.1-1.6
	- letmedespawn 1.2.0
	- levelz 1.4.12
	- libz 1.0.3
	- lithium 0.11.2
	- logbegone 1.0.8
	- lostrelics 1.20-1
	- lychee 5.1.4
	- magic_vibe_decorations 1.7.0
	- magistuarmory 8.11
	- majruszlibrary 7.0.3
	- majruszsaccessories 1.4.0
	- majruszsenchantments 1.10.5
	- map_atlases 1.20-2.7.6
	- maxhealthfix 12.0.2
	- mca 7.5.11+1.20.1
	- mcda 5.0.1
	- mcdar 3.0.0
	- mcde 1.5.4.1-1.20
	- mcdw 8.1.0
	- mcwholidays 1.1.0
	- mcwlights 1.0.6
	- memoryleakfix 1.1.2
	- midnightlib 1.4.1
	- minecraft 1.20.1
	- modernfix 5.11.1+mc1.20.1
	- modmenu 7.2.2
	- modmenu-badges-lib 2023.6.1
	- moonlight 1.20-2.8.79
	- moreculling 1.20.1-0.19.0
	- morecullingextra 1.1-1.20.1
	- moremobs 1.5.1+mod
	- mousetweaks 2.25
	- mru 0.4.0+1.20
	- mythicmetals 0.19.2+1.20.1
	- mythicmobs 1.20.1-connector-1.4.5
	- nature_arise 0.6.0B
	- naturescompass 1.20.1-2.2.3-fabric
	- netherportalfix 13.0.1
	- nethersdelight 1.0.0
	- nethervinery 1.2.2
	- numismatic-overhaul 0.2.12+1.20.1
	- owo 0.11.2+1.20
	- paladins 1.0.4+1.20.1
	- patchouli 1.20.1-84-FABRIC
	- pehkui 3.7.12+1.14.4-1.20.4
	- ping-wheel 1.7.1
	- placeable_food 1.2.0
	- player-animator 1.0.2-rc1+1.20
	- playerex 3.6.0+1.20.1
	- presencefootsteps 1.9.0
	- prism 1.0.5
	- projectile_damage 3.2.2+1.20.1
	- puffish_skills 0.11.2
	- pumpeddesertfabric 1.0.0
	- recipeessentials 1.20.1-3.2
	- relicex 3.4.0+1.20.1
	- repurposed_structures 7.1.11+1.20.1-fabric
	- resourcefulconfig 2.1.1
	- resourcefullib 2.1.20
	- rightclickharvest 3.2.3+1.19.x-1.20.1-fabric
	- runes 0.9.10+1.20.1
	- searchables 1.0.2
	- shouldersurfing 2.8.1
	- simplyswords 1.51.5-1.20.1
	- smitherz 1.0.1
	- snowyspirit 1.20-3.0.3
	- snuffles 1.0.0+1.20
	- sodium 0.5.3
	- sound_physics_remastered 1.20.1-1.3.1
	- spell_engine 0.12.4+1.20.1
	- spell_power 0.9.19+1.20.1
	- spellbladenext 1.3
	- starlight 1.1.2+fabric.dbc156f
	- superbsteeds 1.20-1
	- supermartijn642configlib 1.1.8+a
	- supermartijn642corelib 1.1.16
	- supplementaries 1.20-2.7.21
	- suppsquared 1.20-1.1.12
	- t_and_t 1.12
	- tectonic 2.1.1
	- terrablender 3.0.0.169
	- the_bumblezone 7.1.14+1.20.1-fabric
	- thekatanasmod 1.1.1
	- tooltipfix 1.1.1-1.20
	- travel_friendly_food 1.0.0
	- tridents_n_stuff 0.1.1+1.20.1
	- trinkets 3.7.1
	- twigs 3.1.0
	- ubesdelight 0.1.5b
	- uilib 0.2.11
	- valentines_blessing 1.5.0
	- variantvanillablocks 1.3.6
	- vcinteraction 1.20.1-1.0.6
	- vinery 1.4.7
	- vmp 0.2.0+beta.7.102
	- voicechat 1.20.1-2.4.32
	- wacot 1.20.1-0.1.1
	- watut 1.20.1-1.0.12
	- waystones 14.1.3
	- weaponmaster 3.0.5
	- wilderwild 2.2.3-Fabric+1.20.1
	- winterly 0.9.3+1.20
	- wizards 1.0.4+1.20.1
	- yet_another_config_lib_v3 3.2.1+1.20

**Comment by pokesmells** [comment]
This has been fixed in version [0.3.1](https://www.curseforge.com/minecraft/mc-mods/relicex-directors-cut/files/5023659) please check it out!
